name: Run Robot Framework Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Setup Python Virtual Environment
        run: |
            pwd
            python --version
            python -m venv .venv
                  
      - name: Set Poetry Path
        run: echo "POETRY_HOME=C:\Users\runneradmin\AppData\Roaming\Python\Scripts" >> $GITHUB_ENV
      
      - name: Add Poetry to PATH
        run: echo "$POETRY_HOME" >> $GITHUB_PATH
      
      - name: Install Poetry
        run: python -m pip install poetry==2.2.1
      
      - name: Check Poetry Version
        run: poetry --version
            
      - name: Install dependencies
        run: |
          echo 'if (-not (Get-Command poetry -ErrorAction Ignore)) { $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts" }' | Out-File -Append $PROFILE
          python -m pip install --upgrade pip
          # Install additional dependencies if needed
          poetry install

      - name: Run Robot Framework tests
        run: |
          echo 'if (-not (Get-Command poetry -ErrorAction Ignore)) { $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Scripts" }' | Out-File -Append $PROFILE
          poetry run robot -d results .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3
